import 'bootstrap/dist/css/bootstrap.css';
import React from "react";
import BootstrapClient from '@/components/BootstrapClient';
import {Metadata} from "next";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>): React.JSX.Element {
    return (
        <html lang="en" data-bs-theme="dark">
        <body className="d-flex vh-100 flex-column">
        {children}
        <BootstrapClient/>
        </body>
        </html>
    )
}